// Generated by Tools/Forge/build-primitive-runtime.ts. Do not hand edit.
// Sources: primitive/primitives.json + behavior/operators.json; contract SHA-256 7db73fb9b17d16a3c4a82a8e108551ab506c1deb6a290b4425cc400d9e1b73a8
namespace ForgeRuntime.Framework;

internal static class PrimitiveContracts
{
    internal const string HealCapabilityJson = """
    {
      "id": "forge.action.combat.heal",
      "owner": "forge.contract.combat",
      "kind": "action",
      "label": "治疗目标",
      "version": "1.0.0",
      "parameters": {
        "description": "给你选中的目标回血。溢出规则：截断只回到上限；丢弃是会溢出就整次不治疗；溢出允许超过上限，做不到的目标会拒绝。",
        "summary": "给你选中的目标回血。溢出规则：截断只回到上限；丢弃是会溢出就整次不治疗；溢出允许超过上限，做不到的目标会拒绝。",
        "summaryEn": "Puts health back on the targets you picked. Clamp stops at maximum health; discard skips the whole heal if it would overflow; overheal may exceed the maximum, and targets that cannot are rejected.",
        "labelEn": "Heal",
        "support": "authoring-contract-only"
      },
      "graph": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "source",
            "type": "entity",
            "entityKinds": [
              "gtfo.player",
              "gtfo.enemy",
              "gtfo.map_object",
              "gtfo.level_object",
              "gtfo.level",
              "gtfo.zone",
              "gtfo.equipment"
            ]
          },
          {
            "id": "amount",
            "type": "number",
            "unit": "hp"
          },
          {
            "id": "cap",
            "type": "number",
            "unit": "hp",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "result",
            "type": "result",
            "schema": "forge.result.combat.heal",
            "codes": [
              "overheal-unsupported",
              "amount-out-of-range",
              "invalid-cap",
              "too-many-targets",
              "authority-or-phase",
              "not-attempted-after-unknown-commit",
              "stale-or-unsupported-recipient",
              "missing-health-receiver",
              "health-receiver-owner-mismatch",
              "not-alive",
              "invalid-health-state",
              "would-overheal",
              "quantization-failed",
              "state-changed-before-commit",
              "preflight-exception",
              "receiver-changed-during-commit",
              "unexpected-health-readback",
              "native-commit-exception",
              "readback-exception",
              "heal-all-rejected",
              "heal-all-unknown"
            ],
            "fields": [
              {
                "id": "target",
                "type": "entity"
              },
              {
                "id": "status",
                "type": "enum",
                "schema": "execution_outcome"
              },
              {
                "id": "committed",
                "type": "enum",
                "schema": "commit_state"
              },
              {
                "id": "code",
                "type": "string"
              },
              {
                "id": "amount",
                "type": "number",
                "unit": "hp"
              },
              {
                "id": "target_count",
                "type": "integer"
              }
            ]
          }
        ],
        "parameters": [
          {
            "id": "overheal_policy",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "clamp",
              "discard",
              "overheal"
            ]
          }
        ],
        "recipients": {
          "input": "targets",
          "target": "entity",
          "cardinality": "many",
          "requires": [
            "health.heal"
          ],
          "result": "result"
        }
      }
    }
    """;
    internal const string EnemySpawnedCapabilityJson = """
    {
      "id": "forge.trigger.enemy.spawned",
      "owner": "forge.contract.trigger",
      "kind": "trigger",
      "label": "敌人生成完成",
      "version": "1.0.0",
      "parameters": {
        "description": "敌人实例已经完成生成并具有可用身份。",
        "summary": "敌人实例已经完成生成并具有可用身份。",
        "summaryEn": "Fires when an enemy instance has finished spawning and has a usable identity.",
        "labelEn": "Enemy spawned",
        "support": "authoring-contract-only"
      },
      "graph": {
        "domains": [
          "map",
          "room",
          "enemy",
          "logic"
        ],
        "execution": "host",
        "inputs": [],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "enemy",
            "type": "entity",
            "entityKinds": [
              "gtfo.enemy"
            ]
          },
          {
            "id": "position",
            "type": "vector3",
            "unit": "m"
          }
        ],
        "parameters": []
      }
    }
    """;
}

internal static class BehaviorOperatorContracts
{
    private const string ControlGraphsJson = """
    {
      "branch": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "condition",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "then",
            "type": "execution"
          },
          {
            "id": "otherwise",
            "type": "execution"
          }
        ],
        "parameters": []
      },
      "sequence": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          }
        ],
        "outputs": [
          {
            "id": "step_1",
            "type": "execution"
          },
          {
            "id": "step_2",
            "type": "execution"
          }
        ],
        "parameters": [
          {
            "id": "step_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "outputs",
          "parameter": "step_count",
          "port": {
            "id": "step",
            "type": "execution"
          }
        }
      },
      "delay": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "duration",
            "type": "integer",
            "unit": "tick"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": []
      },
      "interval": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "interval",
            "type": "integer",
            "unit": "tick"
          },
          {
            "id": "count",
            "type": "integer",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "pulse",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": [
          {
            "id": "first_pulse",
            "type": "enum",
            "role": "structural",
            "required": true,
            "set": "pulse_start"
          }
        ]
      },
      "cancel": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "task",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "cancelled",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "for_each": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "candidates",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "budget",
            "type": "integer"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "body",
            "type": "execution"
          },
          {
            "id": "item",
            "type": "entity",
            "entityKindsFrom": "candidates"
          },
          {
            "id": "index",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "present": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "present",
            "type": "execution"
          },
          {
            "id": "missing",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "entityKindsFrom": "value"
          }
        ],
        "parameters": [
          {
            "id": "value_type",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "number",
              "integer",
              "boolean",
              "string",
              "entity",
              "vector3",
              "handle:timer",
              "handle:subscription",
              "handle:effect"
            ]
          }
        ]
      }
    }
    """;
    internal static readonly System.Text.Json.JsonElement ControlGraphs = RuntimeJson.Parse(ControlGraphsJson);
}

/// <summary>Reviewed dynamic Primitive graphs. Registration-time use only.</summary>
public static class PrimitiveGraphSource
{
    private const string Json = """
    {
      "forge.action.combat.heal": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "source",
            "type": "entity",
            "entityKinds": [
              "gtfo.player",
              "gtfo.enemy",
              "gtfo.map_object",
              "gtfo.level_object",
              "gtfo.level",
              "gtfo.zone",
              "gtfo.equipment"
            ]
          },
          {
            "id": "amount",
            "type": "number",
            "unit": "hp"
          },
          {
            "id": "cap",
            "type": "number",
            "unit": "hp",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "result",
            "type": "result",
            "schema": "forge.result.combat.heal",
            "codes": [
              "overheal-unsupported",
              "amount-out-of-range",
              "invalid-cap",
              "too-many-targets",
              "authority-or-phase",
              "not-attempted-after-unknown-commit",
              "stale-or-unsupported-recipient",
              "missing-health-receiver",
              "health-receiver-owner-mismatch",
              "not-alive",
              "invalid-health-state",
              "would-overheal",
              "quantization-failed",
              "state-changed-before-commit",
              "preflight-exception",
              "receiver-changed-during-commit",
              "unexpected-health-readback",
              "native-commit-exception",
              "readback-exception",
              "heal-all-rejected",
              "heal-all-unknown"
            ],
            "fields": [
              {
                "id": "target",
                "type": "entity"
              },
              {
                "id": "status",
                "type": "enum",
                "schema": "execution_outcome"
              },
              {
                "id": "committed",
                "type": "enum",
                "schema": "commit_state"
              },
              {
                "id": "code",
                "type": "string"
              },
              {
                "id": "amount",
                "type": "number",
                "unit": "hp"
              },
              {
                "id": "target_count",
                "type": "integer"
              }
            ]
          }
        ],
        "parameters": [
          {
            "id": "overheal_policy",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "clamp",
              "discard",
              "overheal"
            ]
          }
        ],
        "recipients": {
          "input": "targets",
          "target": "entity",
          "cardinality": "many",
          "requires": [
            "health.heal"
          ],
          "result": "result"
        }
      },
      "forge.action.map.spawn_commit": {
        "domains": [
          "map",
          "room",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "solution",
            "type": "handle",
            "handleKind": "request",
            "lifetime": "encounter"
          },
          {
            "id": "map",
            "type": "resource",
            "resourceKind": "map",
            "schema": "forge.resource.map"
          },
          {
            "id": "validation_revision",
            "type": "string"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "result",
            "type": "result",
            "schema": "forge.result.map.spawn_commit",
            "fields": [
              {
                "id": "target",
                "type": "entity"
              },
              {
                "id": "status",
                "type": "enum",
                "schema": "execution_outcome"
              },
              {
                "id": "committed",
                "type": "enum",
                "schema": "commit_state"
              },
              {
                "id": "code",
                "type": "string"
              }
            ]
          },
          {
            "id": "spawned",
            "type": "entity",
            "cardinality": "many",
            "entityKinds": [
              "gtfo.enemy"
            ]
          }
        ],
        "parameters": [
          {
            "id": "intent",
            "type": "enum",
            "role": "structural",
            "required": false,
            "values": [
              "sleeping",
              "attacking",
              "patrolling"
            ],
            "set": "ai_state"
          }
        ],
        "recipients": {
          "input": "solution",
          "target": "handle",
          "cardinality": "one",
          "requires": [
            "spawn.commit"
          ],
          "result": "result"
        }
      },
      "forge.trigger.enemy.spawned": {
        "domains": [
          "map",
          "room",
          "enemy",
          "logic"
        ],
        "execution": "host",
        "inputs": [],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "enemy",
            "type": "entity",
            "entityKinds": [
              "gtfo.enemy"
            ]
          },
          {
            "id": "position",
            "type": "vector3",
            "unit": "m"
          }
        ],
        "parameters": []
      }
    }
    """;
    private static readonly System.Text.Json.JsonElement Graphs = RuntimeJson.Parse(Json);
    public static System.Text.Json.JsonElement Get(string id) => Graphs.GetProperty(id);
}

/// <summary>Reviewed Behavior Operator graphs. They compose behavior and are not gameplay primitives.</summary>
public static class BehaviorOperatorGraphSource
{
    private const string Json = """
    {
      "forge.control.flow.branch": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "condition",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "then",
            "type": "execution"
          },
          {
            "id": "otherwise",
            "type": "execution"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.sequence": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          }
        ],
        "outputs": [
          {
            "id": "step_1",
            "type": "execution"
          },
          {
            "id": "step_2",
            "type": "execution"
          }
        ],
        "parameters": [
          {
            "id": "step_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "outputs",
          "parameter": "step_count",
          "port": {
            "id": "step",
            "type": "execution"
          }
        }
      },
      "forge.control.flow.delay": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "duration",
            "type": "integer",
            "unit": "tick"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.interval": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "interval",
            "type": "integer",
            "unit": "tick"
          },
          {
            "id": "count",
            "type": "integer",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "pulse",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": [
          {
            "id": "first_pulse",
            "type": "enum",
            "role": "structural",
            "required": true,
            "set": "pulse_start"
          }
        ]
      },
      "forge.control.flow.cancel": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "task",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "cancelled",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.for_each": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "candidates",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "budget",
            "type": "integer"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "body",
            "type": "execution"
          },
          {
            "id": "item",
            "type": "entity",
            "entityKindsFrom": "candidates"
          },
          {
            "id": "index",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.present": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "present",
            "type": "execution"
          },
          {
            "id": "missing",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "entityKindsFrom": "value"
          }
        ],
        "parameters": [
          {
            "id": "value_type",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "number",
              "integer",
              "boolean",
              "string",
              "entity",
              "vector3",
              "handle:timer",
              "handle:subscription",
              "handle:effect"
            ]
          }
        ]
      },
      "forge.query.entity.position": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "entity",
            "type": "entity"
          }
        ],
        "outputs": [
          {
            "id": "position",
            "type": "vector3",
            "unit": "m"
          }
        ],
        "parameters": []
      },
      "forge.modifier.value.add": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "a",
            "type": "number"
          },
          {
            "id": "b",
            "type": "number"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "number"
          }
        ],
        "parameters": [
          {
            "id": "input_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "inputs",
          "parameter": "input_count",
          "port": {
            "id": "input",
            "type": "number"
          }
        }
      },
      "forge.modifier.value.multiply": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "a",
            "type": "number"
          },
          {
            "id": "b",
            "type": "number"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "number"
          }
        ],
        "parameters": [
          {
            "id": "input_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "inputs",
          "parameter": "input_count",
          "port": {
            "id": "input",
            "type": "number"
          }
        }
      },
      "forge.selector.target.players": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [],
        "outputs": [
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many",
            "entityKinds": [
              "gtfo.player"
            ]
          }
        ],
        "parameters": []
      },
      "forge.selector.target.enemies": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [],
        "outputs": [
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many",
            "entityKinds": [
              "gtfo.enemy"
            ]
          }
        ],
        "parameters": []
      },
      "forge.selector.target.zone_members": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "candidates",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "zone",
            "type": "resource",
            "resourceKind": "zone",
            "schema": "forge.resource.zone"
          }
        ],
        "outputs": [
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many",
            "entityKindsFrom": "candidates"
          }
        ],
        "parameters": [
          {
            "id": "empty",
            "type": "enum",
            "role": "structural",
            "required": true,
            "set": "empty_policy"
          }
        ]
      },
      "forge.condition.predicate.compare": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "left",
            "type": "entity",
            "valueTypeParameter": "value_type"
          },
          {
            "id": "right",
            "type": "entity",
            "valueTypeParameter": "value_type"
          },
          {
            "id": "operator",
            "type": "enum",
            "schema": "compare_operator"
          },
          {
            "id": "tolerance",
            "type": "number",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "boolean"
          }
        ],
        "parameters": [
          {
            "id": "value_type",
            "type": "enum",
            "role": "structural",
            "required": false,
            "values": [
              "number",
              "integer",
              "string",
              "entity"
            ]
          }
        ],
        "reads": [
          "world"
        ]
      },
      "forge.condition.predicate.all": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "a",
            "type": "boolean"
          },
          {
            "id": "b",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "boolean"
          }
        ],
        "parameters": [
          {
            "id": "input_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "inputs",
          "parameter": "input_count",
          "port": {
            "id": "input",
            "type": "boolean"
          }
        }
      },
      "forge.condition.predicate.any": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "a",
            "type": "boolean"
          },
          {
            "id": "b",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "boolean"
          }
        ],
        "parameters": [
          {
            "id": "input_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "inputs",
          "parameter": "input_count",
          "port": {
            "id": "input",
            "type": "boolean"
          }
        }
      },
      "forge.condition.predicate.not": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "input",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "boolean"
          }
        ],
        "parameters": []
      },
      "forge.query.entity.health": {
        "domains": [
          "map",
          "enemy",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "entity",
            "type": "entity",
            "entityKinds": [
              "gtfo.player",
              "gtfo.enemy"
            ]
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "number",
            "unit": "hp"
          },
          {
            "id": "maximum",
            "type": "number",
            "unit": "hp"
          },
          {
            "id": "fraction",
            "type": "number"
          }
        ],
        "parameters": []
      },
      "forge.selector.target.event_target": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [],
        "outputs": [
          {
            "id": "target",
            "type": "entity",
            "nullable": true
          }
        ],
        "parameters": []
      },
      "forge.selector.target.zone": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "anchor",
            "type": "entity"
          }
        ],
        "outputs": [
          {
            "id": "zone",
            "type": "resource",
            "resourceKind": "zone",
            "schema": "forge.resource.zone",
            "nullable": true
          }
        ],
        "parameters": []
      },
      "forge.condition.enum.compare": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "value",
            "type": "enum",
            "schemaParameter": "enum_set",
            "nullable": true
          },
          {
            "id": "equals",
            "type": "enum",
            "schemaParameter": "enum_set"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "boolean"
          }
        ],
        "parameters": [
          {
            "id": "enum_set",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "compare_operator",
              "boundary_mode",
              "rounding_mode",
              "command_phase",
              "execution_outcome",
              "interaction_phase",
              "damage_kind",
              "ai_state",
              "status_kind",
              "stack_policy",
              "query_shape",
              "empty_policy",
              "equipment_action",
              "lifetime_scope",
              "variable_value_type",
              "recipient_sort",
              "recipient_anchor",
              "recipient_relation",
              "recipient_life_state",
              "value_operation",
              "coordinate_space",
              "pulse_start",
              "commit_state",
              "agent_modifier",
              "rundown_tier",
              "door_state",
              "door_query_state",
              "door_phase",
              "equipment_kind",
              "supply_kind",
              "pickup_kind",
              "scan_state",
              "container_state",
              "door_lock_cause",
              "enemy_group_state",
              "charge_phase",
              "aim_phase",
              "shot_outcome",
              "player_movement_state",
              "enemy_group_type"
            ]
          }
        ]
      },
      "forge.modifier.value.map_range": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "value",
            "type": "number"
          },
          {
            "id": "input_min",
            "type": "number"
          },
          {
            "id": "input_max",
            "type": "number"
          },
          {
            "id": "input_floor",
            "type": "number"
          },
          {
            "id": "input_ceiling",
            "type": "number"
          },
          {
            "id": "output_min",
            "type": "number"
          },
          {
            "id": "output_max",
            "type": "number"
          },
          {
            "id": "exponent",
            "type": "number"
          },
          {
            "id": "flip",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "number"
          }
        ],
        "parameters": [
          {
            "id": "input_unit",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "absolute",
              "relative",
              "normalized"
            ]
          },
          {
            "id": "bounds",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "clamp",
              "allow",
              "reject"
            ]
          }
        ]
      }
    }
    """;
    private static readonly System.Text.Json.JsonElement Graphs = RuntimeJson.Parse(Json);
    public static System.Text.Json.JsonElement Get(string id) => Graphs.GetProperty(id);
}
