// Generated by Tools/Forge/build-primitive-runtime.ts. Do not hand edit.
// Source: Docs/forge-contract/primitive/primitives.json; contract SHA-256 8a2379f31f84cd6372c0340e9d5f67aad3a4b37fe142685d6ad2c3981010e7bb
namespace ForgeRuntime.Framework;

internal static class PrimitiveContracts
{
    internal const string HealCapabilityJson = """
    {
      "id": "forge.action.combat.heal",
      "owner": "forge.contract.combat",
      "kind": "action",
      "label": "治疗目标",
      "version": "1.0.0",
      "parameters": {
        "description": "给你选中的目标回血。溢出规则：截断只回到上限；丢弃是会溢出就整次不治疗；溢出允许超过上限，做不到的目标会拒绝。",
        "summary": "给你选中的目标回血。溢出规则：截断只回到上限；丢弃是会溢出就整次不治疗；溢出允许超过上限，做不到的目标会拒绝。",
        "summaryEn": "Puts health back on the targets you picked. Clamp stops at maximum health; discard skips the whole heal if it would overflow; overheal may exceed the maximum, and targets that cannot are rejected.",
        "labelEn": "Heal",
        "support": "authoring-contract-only"
      },
      "graph": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "source",
            "type": "entity",
            "entityKinds": [
              "gtfo.player",
              "gtfo.enemy",
              "gtfo.map_object",
              "gtfo.level_object",
              "gtfo.level",
              "gtfo.zone",
              "gtfo.equipment"
            ]
          },
          {
            "id": "amount",
            "type": "number",
            "unit": "hp"
          },
          {
            "id": "cap",
            "type": "number",
            "unit": "hp",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "result",
            "type": "result",
            "schema": "forge.result.combat.heal",
            "codes": [
              "overheal-unsupported",
              "amount-out-of-range",
              "invalid-cap",
              "too-many-targets",
              "authority-or-phase",
              "not-attempted-after-unknown-commit",
              "stale-or-unsupported-recipient",
              "missing-health-receiver",
              "health-receiver-owner-mismatch",
              "not-alive",
              "invalid-health-state",
              "would-overheal",
              "quantization-failed",
              "state-changed-before-commit",
              "preflight-exception",
              "receiver-changed-during-commit",
              "unexpected-health-readback",
              "native-commit-exception",
              "readback-exception",
              "heal-all-rejected",
              "heal-all-unknown"
            ],
            "fields": [
              {
                "id": "target",
                "type": "entity"
              },
              {
                "id": "status",
                "type": "enum",
                "schema": "execution_outcome"
              },
              {
                "id": "committed",
                "type": "enum",
                "schema": "commit_state"
              },
              {
                "id": "code",
                "type": "string"
              },
              {
                "id": "amount",
                "type": "number",
                "unit": "hp"
              },
              {
                "id": "target_count",
                "type": "integer"
              }
            ]
          }
        ],
        "parameters": [
          {
            "id": "overheal_policy",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "clamp",
              "discard",
              "overheal"
            ]
          }
        ],
        "recipients": {
          "input": "targets",
          "target": "entity",
          "cardinality": "many",
          "requires": [
            "health.heal"
          ],
          "result": "result"
        }
      }
    }
    """;
    private const string ControlGraphsJson = """
    {
      "branch": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "condition",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "then",
            "type": "execution"
          },
          {
            "id": "otherwise",
            "type": "execution"
          }
        ],
        "parameters": []
      },
      "sequence": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          }
        ],
        "outputs": [
          {
            "id": "step_1",
            "type": "execution"
          },
          {
            "id": "step_2",
            "type": "execution"
          }
        ],
        "parameters": [
          {
            "id": "step_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "outputs",
          "parameter": "step_count",
          "port": {
            "id": "step",
            "type": "execution"
          }
        }
      },
      "delay": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "duration",
            "type": "integer",
            "unit": "tick"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": []
      },
      "interval": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "interval",
            "type": "integer",
            "unit": "tick"
          },
          {
            "id": "count",
            "type": "integer",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "pulse",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": [
          {
            "id": "first_pulse",
            "type": "enum",
            "role": "structural",
            "required": true,
            "set": "pulse_start"
          }
        ]
      },
      "cancel": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "task",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "cancelled",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "for_each": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "candidates",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "budget",
            "type": "integer"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "body",
            "type": "execution"
          },
          {
            "id": "item",
            "type": "entity",
            "entityKindsFrom": "candidates"
          },
          {
            "id": "index",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "present": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "present",
            "type": "execution"
          },
          {
            "id": "missing",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "entityKindsFrom": "value"
          }
        ],
        "parameters": [
          {
            "id": "value_type",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "number",
              "integer",
              "boolean",
              "string",
              "entity",
              "vector3",
              "handle:timer",
              "handle:subscription",
              "handle:effect"
            ]
          }
        ]
      }
    }
    """;
    internal static readonly System.Text.Json.JsonElement ControlGraphs = RuntimeJson.Parse(ControlGraphsJson);
}

/// <summary>Reviewed Primitive graphs. Registration-time use only; not a runtime report.</summary>
public static class PrimitiveGraphSource
{
    private const string Json = """
    {
      "forge.control.flow.branch": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "condition",
            "type": "boolean"
          }
        ],
        "outputs": [
          {
            "id": "then",
            "type": "execution"
          },
          {
            "id": "otherwise",
            "type": "execution"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.sequence": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          }
        ],
        "outputs": [
          {
            "id": "step_1",
            "type": "execution"
          },
          {
            "id": "step_2",
            "type": "execution"
          }
        ],
        "parameters": [
          {
            "id": "step_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "outputs",
          "parameter": "step_count",
          "port": {
            "id": "step",
            "type": "execution"
          }
        }
      },
      "forge.control.flow.delay": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "duration",
            "type": "integer",
            "unit": "tick"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.interval": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "interval",
            "type": "integer",
            "unit": "tick"
          },
          {
            "id": "count",
            "type": "integer",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "pulse",
            "type": "execution"
          },
          {
            "id": "timer",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "parameters": [
          {
            "id": "first_pulse",
            "type": "enum",
            "role": "structural",
            "required": true,
            "set": "pulse_start"
          }
        ]
      },
      "forge.control.flow.cancel": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "task",
            "type": "handle",
            "handleKind": "timer",
            "lifetime": "encounter"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "cancelled",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.for_each": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "candidates",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "budget",
            "type": "integer"
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "body",
            "type": "execution"
          },
          {
            "id": "item",
            "type": "entity",
            "entityKindsFrom": "candidates"
          },
          {
            "id": "index",
            "type": "integer"
          }
        ],
        "parameters": []
      },
      "forge.control.flow.present": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "present",
            "type": "execution"
          },
          {
            "id": "missing",
            "type": "execution"
          },
          {
            "id": "value",
            "type": "entity",
            "valueTypeParameter": "value_type",
            "nullable": true,
            "entityKindsFrom": "value"
          }
        ],
        "parameters": [
          {
            "id": "value_type",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "number",
              "integer",
              "boolean",
              "string",
              "entity",
              "vector3",
              "handle:timer",
              "handle:subscription",
              "handle:effect"
            ]
          }
        ]
      },
      "forge.query.entity.position": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "entity",
            "type": "entity"
          }
        ],
        "outputs": [
          {
            "id": "position",
            "type": "vector3",
            "unit": "m"
          }
        ],
        "parameters": []
      },
      "forge.action.combat.heal": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player"
        ],
        "execution": "host",
        "inputs": [
          {
            "id": "in",
            "type": "execution"
          },
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "source",
            "type": "entity",
            "entityKinds": [
              "gtfo.player",
              "gtfo.enemy",
              "gtfo.map_object",
              "gtfo.level_object",
              "gtfo.level",
              "gtfo.zone",
              "gtfo.equipment"
            ]
          },
          {
            "id": "amount",
            "type": "number",
            "unit": "hp"
          },
          {
            "id": "cap",
            "type": "number",
            "unit": "hp",
            "optional": true
          }
        ],
        "outputs": [
          {
            "id": "next",
            "type": "execution"
          },
          {
            "id": "result",
            "type": "result",
            "schema": "forge.result.combat.heal",
            "codes": [
              "overheal-unsupported",
              "amount-out-of-range",
              "invalid-cap",
              "too-many-targets",
              "authority-or-phase",
              "not-attempted-after-unknown-commit",
              "stale-or-unsupported-recipient",
              "missing-health-receiver",
              "health-receiver-owner-mismatch",
              "not-alive",
              "invalid-health-state",
              "would-overheal",
              "quantization-failed",
              "state-changed-before-commit",
              "preflight-exception",
              "receiver-changed-during-commit",
              "unexpected-health-readback",
              "native-commit-exception",
              "readback-exception",
              "heal-all-rejected",
              "heal-all-unknown"
            ],
            "fields": [
              {
                "id": "target",
                "type": "entity"
              },
              {
                "id": "status",
                "type": "enum",
                "schema": "execution_outcome"
              },
              {
                "id": "committed",
                "type": "enum",
                "schema": "commit_state"
              },
              {
                "id": "code",
                "type": "string"
              },
              {
                "id": "amount",
                "type": "number",
                "unit": "hp"
              },
              {
                "id": "target_count",
                "type": "integer"
              }
            ]
          }
        ],
        "parameters": [
          {
            "id": "overheal_policy",
            "type": "enum",
            "role": "structural",
            "required": true,
            "values": [
              "clamp",
              "discard",
              "overheal"
            ]
          }
        ],
        "recipients": {
          "input": "targets",
          "target": "entity",
          "cardinality": "many",
          "requires": [
            "health.heal"
          ],
          "result": "result"
        }
      },
      "forge.modifier.value.add": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "a",
            "type": "number"
          },
          {
            "id": "b",
            "type": "number"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "number"
          }
        ],
        "parameters": [
          {
            "id": "input_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "inputs",
          "parameter": "input_count",
          "port": {
            "id": "input",
            "type": "number"
          }
        }
      },
      "forge.modifier.value.multiply": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "pure",
        "inputs": [
          {
            "id": "a",
            "type": "number"
          },
          {
            "id": "b",
            "type": "number"
          }
        ],
        "outputs": [
          {
            "id": "value",
            "type": "number"
          }
        ],
        "parameters": [
          {
            "id": "input_count",
            "type": "integer",
            "role": "structural",
            "required": false,
            "minimum": 2,
            "maximum": 32
          }
        ],
        "variadic": {
          "side": "inputs",
          "parameter": "input_count",
          "port": {
            "id": "input",
            "type": "number"
          }
        }
      },
      "forge.selector.target.players": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [],
        "outputs": [
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many",
            "entityKinds": [
              "gtfo.player"
            ]
          }
        ],
        "parameters": []
      },
      "forge.selector.target.enemies": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [],
        "outputs": [
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many",
            "entityKinds": [
              "gtfo.enemy"
            ]
          }
        ],
        "parameters": []
      },
      "forge.selector.target.zone_members": {
        "domains": [
          "map",
          "room",
          "enemy",
          "weapon",
          "tool",
          "consumable",
          "player",
          "logic"
        ],
        "execution": "query",
        "inputs": [
          {
            "id": "candidates",
            "type": "entity",
            "cardinality": "many"
          },
          {
            "id": "zone",
            "type": "resource",
            "resourceKind": "zone",
            "schema": "forge.resource.zone"
          }
        ],
        "outputs": [
          {
            "id": "targets",
            "type": "entity",
            "cardinality": "many",
            "entityKindsFrom": "candidates"
          }
        ],
        "parameters": [
          {
            "id": "empty",
            "type": "enum",
            "role": "structural",
            "required": true,
            "set": "empty_policy"
          }
        ]
      }
    }
    """;
    private static readonly System.Text.Json.JsonElement Graphs = RuntimeJson.Parse(Json);
    public static System.Text.Json.JsonElement Get(string id) => Graphs.GetProperty(id);
}
