// Generated by ForgeRuntime/tools/NetworkMessagesGen: the message layout lives in that tool's field tables, so a
// layout change is a change there plus a rerun. Do not edit this file by hand.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;

namespace ForgeRuntime.Network;

// Generated layout: one flat struct per message, primitive fields only. A nested struct makes Marshal.SizeOf pad it,
// and a padded Marshal image is not the byte body the codec writes, so every field lives in the same struct and
// Marshal.SizeOf<T>() stays equal to the codec's own offset walk.
//
// A text slot is a `ushort` length prefix followed by its content, declared as consecutive fields, so one slot is
// `NetworkProtocol.TextSlotBytes + sizeof(ushort)` bytes of the Marshal image and the codec copies that image whole.

/// <summary>Which side of the authority split a participant runs as.</summary>
internal enum SessionRole : byte
{
    Unknown = 0,
    Host = 1,
    Client = 2
}

/// <summary>Why a world moved on. Only the host ever evaluates a reason; receivers carry it for diagnostics.</summary>
internal enum WorldChangeReason : byte
{
    Unknown = 0,
    NewGeneration = 1,
    LevelCleanup = 2,
    // 3 was the checkpoint suspension. A checkpoint reload continues the same expedition and no longer suspends
    // the runtime, so nothing produces it; the number stays retired rather than reused, because the protocol's
    // values are frozen and a peer that still carries it must keep meaning what it meant.
    /// <summary>The host took itself out of the world: an unsupported host migration, a fault in a native
    /// callback, or the runtime stopping. A receiver carries the byte without switching on it.</summary>
    HostSuspend = 4
}

/// <summary>Result status vocabulary, mirroring the runtime kernel's command statuses on the wire.</summary>
internal static class NetworkStatus
{
    internal const byte Committed = 1;
    internal const byte Succeeded = 2;
    internal const byte Partial = 3;
    internal const byte Rejected = 4;
    internal const byte Failed = 5;
    internal const byte Cancelled = 6;
    internal const byte Expired = 7;
}

/// <summary>Commit-state vocabulary, mirroring the runtime kernel's commit states on the wire.</summary>
internal static class NetworkCommitState
{
    internal const byte None = 0;
    internal const byte Confirmed = 1;
    internal const byte Unknown = 2;
}

/// <summary>Message kinds. Values are frozen with the protocol version.</summary>
internal enum NetworkMessageKind : byte
{
    Hello = 1,
    HelloAck = 2,
    WorldEpoch = 3,
    CommandRequest = 4,
    CommandResult = 5,
    Fact = 6,
    Variables = 7
}

/// <summary>
/// One participant's runtime identity plus a summary of its plan set. Both directions carry it: the host
/// checks the joining client against its own, and the client checks the host, so an unmatched pairing suspends that
/// client's Forge on either side of the decision. The plan set travels as its count and one 32-byte digest — the
/// rows themselves are never on the wire — so the hello is four identity text slots wide.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct HelloMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public byte Role;
    public byte PlanCount;
    public ushort Reserved2;
    public ulong Digest0;
    public ulong Digest1;
    public ulong Digest2;
    public ulong Digest3;
    public ushort L0;
    public ushort L1;
    public ushort L2;
    public ushort L3;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    private ulong S1_W00;
    private ulong S1_W01;
    private ulong S1_W02;
    private ulong S1_W03;

    private ulong S1_W04;
    private ulong S1_W05;
    private ulong S1_W06;
    private ulong S1_W07;

    private ulong S1_W08;
    private ulong S1_W09;
    private ulong S1_W0A;
    private ulong S1_W0B;

    private ulong S1_W0C;
    private ulong S1_W0D;
    private ulong S1_W0E;
    private ulong S1_W0F;

    private ulong S2_W00;
    private ulong S2_W01;
    private ulong S2_W02;
    private ulong S2_W03;

    private ulong S2_W04;
    private ulong S2_W05;
    private ulong S2_W06;
    private ulong S2_W07;

    private ulong S2_W08;
    private ulong S2_W09;
    private ulong S2_W0A;
    private ulong S2_W0B;

    private ulong S2_W0C;
    private ulong S2_W0D;
    private ulong S2_W0E;
    private ulong S2_W0F;

    private ulong S3_W00;
    private ulong S3_W01;
    private ulong S3_W02;
    private ulong S3_W03;

    private ulong S3_W04;
    private ulong S3_W05;
    private ulong S3_W06;
    private ulong S3_W07;

    private ulong S3_W08;
    private ulong S3_W09;
    private ulong S3_W0A;
    private ulong S3_W0B;

    private ulong S3_W0C;
    private ulong S3_W0D;
    private ulong S3_W0E;
    private ulong S3_W0F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 48;
    internal const int SlotCount = 4;
    internal const int PayloadCount = 0;
    internal const int DeclaredBytes = 568;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A HelloMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0,         1 => L1,         2 => L2,         3 => L3, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int RuntimeIdSlot = 0;
    internal string RuntimeId { get => SlotText(0); set => SetSlotText(0, value); }
    internal const int RuntimeVersionSlot = 1;
    internal string RuntimeVersion { get => SlotText(1); set => SetSlotText(1, value); }
    internal const int ApiVersionSlot = 2;
    internal string ApiVersion { get => SlotText(2); set => SetSlotText(2, value); }
    internal const int GameBuildSlot = 3;
    internal string GameBuild { get => SlotText(3); set => SetSlotText(3, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            case 1: L1 = length; return;
            case 2: L2 = length; return;
            case 3: L3 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>The plan-set digest: SHA-256 over the ordinal-sorted plan rows, 32 bytes in four words.
    /// It is computed once when a plan set is adopted, never per message, and compared instead of the rows.</summary>
    internal Span<ulong> DigestWords() => MemoryMarshal.CreateSpan(ref Digest0, NetworkProtocol.PlanSetDigestBytes / sizeof(ulong));
    internal byte[] PlanSetDigest() => MemoryMarshal.AsBytes(DigestWords()).ToArray();
    internal void SetPlanSetDigest(ReadOnlySpan<byte> digest)
    {
        if (digest.Length != NetworkProtocol.PlanSetDigestBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A plan-set digest is " + NetworkProtocol.PlanSetDigestBytes + " bytes, not " + digest.Length + ".");
        digest.CopyTo(MemoryMarshal.AsBytes(DigestWords()));
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
    internal int SetPayload(int index, byte[]? bytes) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
}

/// <summary>
/// The host's verdict for one client hello. `Accepted` is the only value that opens the gameplay gate; every
/// other value carries the reason code the client must report when it suspends its own Forge. The host's own
/// identity travels too, so a client can record exactly which build it matched against.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct HelloAckMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public ulong SubjectSession;
    public byte Role;
    public byte Accepted;
    public ushort Reserved2;
    public long HostWorldEpoch;
    public ushort L0;
    public ushort L1;
    public ushort L2;
    public ushort L3;
    public ushort L4;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    private ulong S1_W00;
    private ulong S1_W01;
    private ulong S1_W02;
    private ulong S1_W03;

    private ulong S1_W04;
    private ulong S1_W05;
    private ulong S1_W06;
    private ulong S1_W07;

    private ulong S1_W08;
    private ulong S1_W09;
    private ulong S1_W0A;
    private ulong S1_W0B;

    private ulong S1_W0C;
    private ulong S1_W0D;
    private ulong S1_W0E;
    private ulong S1_W0F;

    private ulong S2_W00;
    private ulong S2_W01;
    private ulong S2_W02;
    private ulong S2_W03;

    private ulong S2_W04;
    private ulong S2_W05;
    private ulong S2_W06;
    private ulong S2_W07;

    private ulong S2_W08;
    private ulong S2_W09;
    private ulong S2_W0A;
    private ulong S2_W0B;

    private ulong S2_W0C;
    private ulong S2_W0D;
    private ulong S2_W0E;
    private ulong S2_W0F;

    private ulong S3_W00;
    private ulong S3_W01;
    private ulong S3_W02;
    private ulong S3_W03;

    private ulong S3_W04;
    private ulong S3_W05;
    private ulong S3_W06;
    private ulong S3_W07;

    private ulong S3_W08;
    private ulong S3_W09;
    private ulong S3_W0A;
    private ulong S3_W0B;

    private ulong S3_W0C;
    private ulong S3_W0D;
    private ulong S3_W0E;
    private ulong S3_W0F;

    private ulong S4_W00;
    private ulong S4_W01;
    private ulong S4_W02;
    private ulong S4_W03;

    private ulong S4_W04;
    private ulong S4_W05;
    private ulong S4_W06;
    private ulong S4_W07;

    private ulong S4_W08;
    private ulong S4_W09;
    private ulong S4_W0A;
    private ulong S4_W0B;

    private ulong S4_W0C;
    private ulong S4_W0D;
    private ulong S4_W0E;
    private ulong S4_W0F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 32;
    internal const int SlotCount = 5;
    internal const int PayloadCount = 0;
    internal const int DeclaredBytes = 682;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A HelloAckMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0,         1 => L1,         2 => L2,         3 => L3,         4 => L4, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int ReasonCodeSlot = 0;
    internal string ReasonCode { get => SlotText(0); set => SetSlotText(0, value); }
    internal const int HostRuntimeIdSlot = 1;
    internal string HostRuntimeId { get => SlotText(1); set => SetSlotText(1, value); }
    internal const int HostRuntimeVersionSlot = 2;
    internal string HostRuntimeVersion { get => SlotText(2); set => SetSlotText(2, value); }
    internal const int HostApiVersionSlot = 3;
    internal string HostApiVersion { get => SlotText(3); set => SetSlotText(3, value); }
    internal const int HostGameBuildSlot = 4;
    internal string HostGameBuild { get => SlotText(4); set => SetSlotText(4, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            case 1: L1 = length; return;
            case 2: L2 = length; return;
            case 3: L3 = length; return;
            case 4: L4 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
    internal int SetPayload(int index, byte[]? bytes) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
}

/// <summary>
/// The host's world epoch and the transition that produced it.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct WorldEpochMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public long WorldEpoch;
    public long PreviousEpoch;
    public byte Reason;
    public byte Reserved2;
    public ushort Reserved3;
    public ushort L0;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 32;
    internal const int SlotCount = 1;
    internal const int PayloadCount = 0;
    internal const int DeclaredBytes = 162;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A WorldEpochMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int DetailSlot = 0;
    internal string Detail { get => SlotText(0); set => SetSlotText(0, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
    internal int SetPayload(int index, byte[]? bytes) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
}

/// <summary>
/// A client-local observation the host must execute once. The request's identity is
/// `(sender session, world epoch, plan id, event id)`; the payload never participates in the key, and the event id
/// is a per-world counter the sender owns rather than a hash.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct CommandRequestMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public long WorldEpoch;
    public ulong EventId;
    public long LifeEpoch;
    public ulong EntityId;
    public int BindingIndex;
    public int NodeIndex;
    public int ScopeKind;
    public int PayloadLength;
    public ushort L0;
    public ushort L1;
    public ushort L2;
    public ushort L3;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    private ulong S1_W00;
    private ulong S1_W01;
    private ulong S1_W02;
    private ulong S1_W03;

    private ulong S1_W04;
    private ulong S1_W05;
    private ulong S1_W06;
    private ulong S1_W07;

    private ulong S1_W08;
    private ulong S1_W09;
    private ulong S1_W0A;
    private ulong S1_W0B;

    private ulong S1_W0C;
    private ulong S1_W0D;
    private ulong S1_W0E;
    private ulong S1_W0F;

    private ulong S2_W00;
    private ulong S2_W01;
    private ulong S2_W02;
    private ulong S2_W03;

    private ulong S2_W04;
    private ulong S2_W05;
    private ulong S2_W06;
    private ulong S2_W07;

    private ulong S2_W08;
    private ulong S2_W09;
    private ulong S2_W0A;
    private ulong S2_W0B;

    private ulong S2_W0C;
    private ulong S2_W0D;
    private ulong S2_W0E;
    private ulong S2_W0F;

    private ulong S3_W00;
    private ulong S3_W01;
    private ulong S3_W02;
    private ulong S3_W03;

    private ulong S3_W04;
    private ulong S3_W05;
    private ulong S3_W06;
    private ulong S3_W07;

    private ulong S3_W08;
    private ulong S3_W09;
    private ulong S3_W0A;
    private ulong S3_W0B;

    private ulong S3_W0C;
    private ulong S3_W0D;
    private ulong S3_W0E;
    private ulong S3_W0F;

    private ulong P0_W00;
    private ulong P0_W01;
    private ulong P0_W02;
    private ulong P0_W03;

    private ulong P0_W04;
    private ulong P0_W05;
    private ulong P0_W06;
    private ulong P0_W07;

    private ulong P0_W08;
    private ulong P0_W09;
    private ulong P0_W0A;
    private ulong P0_W0B;

    private ulong P0_W0C;
    private ulong P0_W0D;
    private ulong P0_W0E;
    private ulong P0_W0F;

    private ulong P0_W10;
    private ulong P0_W11;
    private ulong P0_W12;
    private ulong P0_W13;

    private ulong P0_W14;
    private ulong P0_W15;
    private ulong P0_W16;
    private ulong P0_W17;

    private ulong P0_W18;
    private ulong P0_W19;
    private ulong P0_W1A;
    private ulong P0_W1B;

    private ulong P0_W1C;
    private ulong P0_W1D;
    private ulong P0_W1E;
    private ulong P0_W1F;

    private ulong P0_W20;
    private ulong P0_W21;
    private ulong P0_W22;
    private ulong P0_W23;

    private ulong P0_W24;
    private ulong P0_W25;
    private ulong P0_W26;
    private ulong P0_W27;

    private ulong P0_W28;
    private ulong P0_W29;
    private ulong P0_W2A;
    private ulong P0_W2B;

    private ulong P0_W2C;
    private ulong P0_W2D;
    private ulong P0_W2E;
    private ulong P0_W2F;

    private ulong P0_W30;
    private ulong P0_W31;
    private ulong P0_W32;
    private ulong P0_W33;

    private ulong P0_W34;
    private ulong P0_W35;
    private ulong P0_W36;
    private ulong P0_W37;

    private ulong P0_W38;
    private ulong P0_W39;
    private ulong P0_W3A;
    private ulong P0_W3B;

    private ulong P0_W3C;
    private ulong P0_W3D;
    private ulong P0_W3E;
    private ulong P0_W3F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 60;
    internal const int SlotCount = 4;
    internal const int PayloadCount = 1;
    internal const int DeclaredBytes = 1092;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => MemoryMarshal.AsBytes(index switch
    {
        0 => MemoryMarshal.CreateSpan(ref Unsafe.As<byte, ulong>(ref Unsafe.As<ulong, byte>(ref P0_W00)), 64),
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Payload index " + index + " is out of range.")
    });

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A CommandRequestMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
        body.AsSpan(MetadataBytes + SlotCount * SlotStride, PayloadCount * PayloadStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0,         1 => L1,         2 => L2,         3 => L3, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int PlanIdSlot = 0;
    internal string PlanId { get => SlotText(0); set => SetSlotText(0, value); }
    internal const int ResourceIdSlot = 1;
    internal string ResourceId { get => SlotText(1); set => SetSlotText(1, value); }
    internal const int CommandIdSlot = 2;
    internal string CommandId { get => SlotText(2); set => SetSlotText(2, value); }
    internal const int EndpointSlot = 3;
    internal string Endpoint { get => SlotText(3); set => SetSlotText(3, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            case 1: L1 = length; return;
            case 2: L2 = length; return;
            case 3: L3 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length)
    {
        if (length < 0 || length > PayloadStride) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Payload length " + length + " is out of range.");
        return PayloadStorage(index)[..length].ToArray();
    }

    internal int SetPayload(int index, byte[]? bytes)
    {
        if (bytes == null || bytes.Length == 0) return 0;
        if (bytes.Length > PayloadStride) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Payload of " + bytes.Length + " bytes exceeds the slot capacity.");
        var target = PayloadStorage(index);
        target[..bytes.Length].Clear();
        bytes.CopyTo(target);
        return bytes.Length;
    }
}

/// <summary>
/// A committed command's outcome, sent back to the requester. This is the projection a repeated request is
/// answered with instead of running a second time.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct CommandResultMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public ulong SubjectSession;
    public ulong EventId;
    public long WorldEpoch;
    public byte Status;
    public byte CommitState;
    public ushort Reserved2;
    public int FactCount;
    public ushort L0;
    public ushort L1;
    public ushort L2;
    public ushort L3;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    private ulong S1_W00;
    private ulong S1_W01;
    private ulong S1_W02;
    private ulong S1_W03;

    private ulong S1_W04;
    private ulong S1_W05;
    private ulong S1_W06;
    private ulong S1_W07;

    private ulong S1_W08;
    private ulong S1_W09;
    private ulong S1_W0A;
    private ulong S1_W0B;

    private ulong S1_W0C;
    private ulong S1_W0D;
    private ulong S1_W0E;
    private ulong S1_W0F;

    private ulong S2_W00;
    private ulong S2_W01;
    private ulong S2_W02;
    private ulong S2_W03;

    private ulong S2_W04;
    private ulong S2_W05;
    private ulong S2_W06;
    private ulong S2_W07;

    private ulong S2_W08;
    private ulong S2_W09;
    private ulong S2_W0A;
    private ulong S2_W0B;

    private ulong S2_W0C;
    private ulong S2_W0D;
    private ulong S2_W0E;
    private ulong S2_W0F;

    private ulong S3_W00;
    private ulong S3_W01;
    private ulong S3_W02;
    private ulong S3_W03;

    private ulong S3_W04;
    private ulong S3_W05;
    private ulong S3_W06;
    private ulong S3_W07;

    private ulong S3_W08;
    private ulong S3_W09;
    private ulong S3_W0A;
    private ulong S3_W0B;

    private ulong S3_W0C;
    private ulong S3_W0D;
    private ulong S3_W0E;
    private ulong S3_W0F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 44;
    internal const int SlotCount = 4;
    internal const int PayloadCount = 0;
    internal const int DeclaredBytes = 564;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A CommandResultMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0,         1 => L1,         2 => L2,         3 => L3, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int CodeSlot = 0;
    internal string Code { get => SlotText(0); set => SetSlotText(0, value); }
    internal const int DetailSlot = 1;
    internal string Detail { get => SlotText(1); set => SetSlotText(1, value); }
    internal const int PlanIdSlot = 2;
    internal string PlanId { get => SlotText(2); set => SetSlotText(2, value); }
    internal const int CommandIdSlot = 3;
    internal string CommandId { get => SlotText(3); set => SetSlotText(3, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            case 1: L1 = length; return;
            case 2: L2 = length; return;
            case 3: L3 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
    internal int SetPayload(int index, byte[]? bytes) => throw new NetworkContractException(NetworkCodes.EventNameUnknown, "This message has no payload slot.");
}

/// <summary>
/// A committed fact the host owns: state that affects results but is not carried by the game's own replication.
/// Facts are addressed by the same three-part entity reference the runtime kernel uses, so a fact from a stale
/// world or a dead life can be refused on arrival.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct FactMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public long WorldEpoch;
    public long LifeEpoch;
    public ulong EntityId;
    public ulong Sequence;
    public int BindingIndex;
    public int PayloadLength;
    public ushort L0;
    public ushort L1;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    private ulong S1_W00;
    private ulong S1_W01;
    private ulong S1_W02;
    private ulong S1_W03;

    private ulong S1_W04;
    private ulong S1_W05;
    private ulong S1_W06;
    private ulong S1_W07;

    private ulong S1_W08;
    private ulong S1_W09;
    private ulong S1_W0A;
    private ulong S1_W0B;

    private ulong S1_W0C;
    private ulong S1_W0D;
    private ulong S1_W0E;
    private ulong S1_W0F;

    private ulong P0_W00;
    private ulong P0_W01;
    private ulong P0_W02;
    private ulong P0_W03;

    private ulong P0_W04;
    private ulong P0_W05;
    private ulong P0_W06;
    private ulong P0_W07;

    private ulong P0_W08;
    private ulong P0_W09;
    private ulong P0_W0A;
    private ulong P0_W0B;

    private ulong P0_W0C;
    private ulong P0_W0D;
    private ulong P0_W0E;
    private ulong P0_W0F;

    private ulong P0_W10;
    private ulong P0_W11;
    private ulong P0_W12;
    private ulong P0_W13;

    private ulong P0_W14;
    private ulong P0_W15;
    private ulong P0_W16;
    private ulong P0_W17;

    private ulong P0_W18;
    private ulong P0_W19;
    private ulong P0_W1A;
    private ulong P0_W1B;

    private ulong P0_W1C;
    private ulong P0_W1D;
    private ulong P0_W1E;
    private ulong P0_W1F;

    private ulong P0_W20;
    private ulong P0_W21;
    private ulong P0_W22;
    private ulong P0_W23;

    private ulong P0_W24;
    private ulong P0_W25;
    private ulong P0_W26;
    private ulong P0_W27;

    private ulong P0_W28;
    private ulong P0_W29;
    private ulong P0_W2A;
    private ulong P0_W2B;

    private ulong P0_W2C;
    private ulong P0_W2D;
    private ulong P0_W2E;
    private ulong P0_W2F;

    private ulong P0_W30;
    private ulong P0_W31;
    private ulong P0_W32;
    private ulong P0_W33;

    private ulong P0_W34;
    private ulong P0_W35;
    private ulong P0_W36;
    private ulong P0_W37;

    private ulong P0_W38;
    private ulong P0_W39;
    private ulong P0_W3A;
    private ulong P0_W3B;

    private ulong P0_W3C;
    private ulong P0_W3D;
    private ulong P0_W3E;
    private ulong P0_W3F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 52;
    internal const int SlotCount = 2;
    internal const int PayloadCount = 1;
    internal const int DeclaredBytes = 824;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => MemoryMarshal.AsBytes(index switch
    {
        0 => MemoryMarshal.CreateSpan(ref Unsafe.As<byte, ulong>(ref Unsafe.As<ulong, byte>(ref P0_W00)), 64),
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Payload index " + index + " is out of range.")
    });

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A FactMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
        body.AsSpan(MetadataBytes + SlotCount * SlotStride, PayloadCount * PayloadStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0,         1 => L1, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int PlanIdSlot = 0;
    internal string PlanId { get => SlotText(0); set => SetSlotText(0, value); }
    internal const int DetailSlot = 1;
    internal string Detail { get => SlotText(1); set => SetSlotText(1, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            case 1: L1 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length)
    {
        if (length < 0 || length > PayloadStride) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Payload length " + length + " is out of range.");
        return PayloadStorage(index)[..length].ToArray();
    }

    internal int SetPayload(int index, byte[]? bytes)
    {
        if (bytes == null || bytes.Length == 0) return 0;
        if (bytes.Length > PayloadStride) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Payload of " + bytes.Length + " bytes exceeds the slot capacity.");
        var target = PayloadStorage(index);
        target[..bytes.Length].Clear();
        bytes.CopyTo(target);
        return bytes.Length;
    }
}

/// <summary>
/// The host's variable state: one body per advance, either that advance's own delta or the whole table a
/// late joiner is owed. The snapshot itself is the kernel's own encoded form in the payload slot, and the epoch
/// it names is checked against the client's world before it is applied, so a snapshot from a world this side
/// already left can never land on the objects of the current one.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal struct VariablesMessage
{
    public ushort ProtocolVersion;
    public ushort Reserved;
    public ulong SenderSession;
    public long WorldEpoch;
    public long Sequence;
    public byte Complete;
    public byte Reserved2;
    public ushort Reserved3;
    public int PayloadLength;
    public ushort L0;
    public ushort L1;

    private ulong S0_W00;
    private ulong S0_W01;
    private ulong S0_W02;
    private ulong S0_W03;

    private ulong S0_W04;
    private ulong S0_W05;
    private ulong S0_W06;
    private ulong S0_W07;

    private ulong S0_W08;
    private ulong S0_W09;
    private ulong S0_W0A;
    private ulong S0_W0B;

    private ulong S0_W0C;
    private ulong S0_W0D;
    private ulong S0_W0E;
    private ulong S0_W0F;

    private ulong S1_W00;
    private ulong S1_W01;
    private ulong S1_W02;
    private ulong S1_W03;

    private ulong S1_W04;
    private ulong S1_W05;
    private ulong S1_W06;
    private ulong S1_W07;

    private ulong S1_W08;
    private ulong S1_W09;
    private ulong S1_W0A;
    private ulong S1_W0B;

    private ulong S1_W0C;
    private ulong S1_W0D;
    private ulong S1_W0E;
    private ulong S1_W0F;

    private ulong P0_W00;
    private ulong P0_W01;
    private ulong P0_W02;
    private ulong P0_W03;

    private ulong P0_W04;
    private ulong P0_W05;
    private ulong P0_W06;
    private ulong P0_W07;

    private ulong P0_W08;
    private ulong P0_W09;
    private ulong P0_W0A;
    private ulong P0_W0B;

    private ulong P0_W0C;
    private ulong P0_W0D;
    private ulong P0_W0E;
    private ulong P0_W0F;

    private ulong P0_W10;
    private ulong P0_W11;
    private ulong P0_W12;
    private ulong P0_W13;

    private ulong P0_W14;
    private ulong P0_W15;
    private ulong P0_W16;
    private ulong P0_W17;

    private ulong P0_W18;
    private ulong P0_W19;
    private ulong P0_W1A;
    private ulong P0_W1B;

    private ulong P0_W1C;
    private ulong P0_W1D;
    private ulong P0_W1E;
    private ulong P0_W1F;

    private ulong P0_W20;
    private ulong P0_W21;
    private ulong P0_W22;
    private ulong P0_W23;

    private ulong P0_W24;
    private ulong P0_W25;
    private ulong P0_W26;
    private ulong P0_W27;

    private ulong P0_W28;
    private ulong P0_W29;
    private ulong P0_W2A;
    private ulong P0_W2B;

    private ulong P0_W2C;
    private ulong P0_W2D;
    private ulong P0_W2E;
    private ulong P0_W2F;

    private ulong P0_W30;
    private ulong P0_W31;
    private ulong P0_W32;
    private ulong P0_W33;

    private ulong P0_W34;
    private ulong P0_W35;
    private ulong P0_W36;
    private ulong P0_W37;

    private ulong P0_W38;
    private ulong P0_W39;
    private ulong P0_W3A;
    private ulong P0_W3B;

    private ulong P0_W3C;
    private ulong P0_W3D;
    private ulong P0_W3E;
    private ulong P0_W3F;

    /// <summary>Metadata width, declared slot and payload counts, published as constants so the wire
    /// checks can assert that this layout still matches what the protocol budget was sized for.</summary>
    internal const int MetadataBytes = 36;
    internal const int SlotCount = 2;
    internal const int PayloadCount = 1;
    internal const int DeclaredBytes = 808;

    /// <summary>The content bytes of one text slot: 128 bytes, with no length prefix of its own.</summary>
    internal Span<byte> SlotStorage(int index)
    {
        if (index < 0 || index >= SlotCount) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        return MemoryMarshal.AsBytes(SlotWords().Slice(index * SlotContentStride / sizeof(ulong), SlotContentStride / sizeof(ulong)));
    }

    /// <summary>The content words of every text slot, in declaration order.</summary>
    private Span<ulong> SlotWords() => MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this).S0_W00, SlotCount * SlotContentStride / sizeof(ulong));

    /// <summary>Payload slot storage, one 512-byte slot per call.</summary>
    internal Span<byte> PayloadStorage(int index) => MemoryMarshal.AsBytes(index switch
    {
        0 => MemoryMarshal.CreateSpan(ref Unsafe.As<byte, ulong>(ref Unsafe.As<ulong, byte>(ref P0_W00)), 64),
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Payload index " + index + " is out of range.")
    });

    /// <summary>
    /// Zeroes the slot frames of an encoded body: the text slots, then each payload slot. The codec calls
    /// this on the body it is about to fill, so a slot its caller left unwritten is empty rather than whatever
    /// the message's storage happened to hold.
    /// </summary>
    internal static void ClearFrames(byte[] body)
    {
        if (body == null || body.Length != DeclaredBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "A VariablesMessage body is not its declared width.");
        body.AsSpan(MetadataBytes, SlotCount * SlotStride).Clear();
        body.AsSpan(MetadataBytes + SlotCount * SlotStride, PayloadCount * PayloadStride).Clear();
    }

    /// <summary>Bytes one text slot's content occupies: what a named setter may fill, and what the body reserves after the prefix.</summary>
    internal const int SlotContentStride = NetworkProtocol.TextSlotBytes;

    /// <summary>Bytes one text slot occupies in the byte body: its length prefix plus its content.</summary>
    internal const int SlotStride = NetworkProtocol.TextSlotStride;

    internal ushort SlotLength(int index) => index switch
    {
        0 => L0,         1 => L1, 
        _ => throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.")
    };

    /// <summary>Every text field this message can carry. A slot exists only as an index on the wire, so
    /// each name is declared with its own constant and accessor: no caller has to know a slot number.</summary>
    internal const int CodeSlot = 0;
    internal string Code { get => SlotText(0); set => SetSlotText(0, value); }
    internal const int DetailSlot = 1;
    internal string Detail { get => SlotText(1); set => SetSlotText(1, value); }

    internal void SetSlotLength(int index, ushort length)
    {
        switch (index)
        {
            case 0: L0 = length; return;
            case 1: L1 = length; return;
            default: throw new NetworkContractException(NetworkCodes.FormatInvalid, "Slot index " + index + " is out of range.");
        }
    }

    internal string SlotText(int index)
    {
        var length = SlotLength(index);
        if (length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot length " + length + " exceeds its capacity.");
        if (length == 0) return string.Empty;
        return Encoding.Latin1.GetString(SlotStorage(index)[..length]);
    }

    internal void SetSlotText(int index, string? value)
    {
        value ??= string.Empty;
        if (value.Length > NetworkProtocol.TextSlotBytes) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Text slot overflow: " + value.Length);
        var slot = SlotStorage(index);
        slot.Clear();
        for (var position = 0; position < value.Length; position++)
        {
            var character = value[position];
            if (character > 0xFF) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Text slot is Latin-1 only.");
            slot[position] = (byte)character;
        }
        SetSlotLength(index, (ushort)value.Length);
    }

    /// <summary>Stride of one payload slot in the byte body.</summary>
    internal const int PayloadStride = 512;

    internal byte[] PayloadBytes(int index, int length)
    {
        if (length < 0 || length > PayloadStride) throw new NetworkContractException(NetworkCodes.FormatInvalid, "Payload length " + length + " is out of range.");
        return PayloadStorage(index)[..length].ToArray();
    }

    internal int SetPayload(int index, byte[]? bytes)
    {
        if (bytes == null || bytes.Length == 0) return 0;
        if (bytes.Length > PayloadStride) throw new NetworkContractException(NetworkCodes.PayloadTooLarge, "Payload of " + bytes.Length + " bytes exceeds the slot capacity.");
        var target = PayloadStorage(index);
        target[..bytes.Length].Clear();
        bytes.CopyTo(target);
        return bytes.Length;
    }
}

/// <summary>
/// One decoded message: the kind discriminator plus the struct for that kind. The transport hands a typed payload
/// straight to this layer, so the struct arrives already Marshal-decoded and only the kind tag is added here.
/// </summary>
internal readonly struct NetworkEnvelope
{
    private NetworkEnvelope(NetworkMessageKind kind, ulong sender)
    {
        Kind = kind;
        Sender = sender;
        Hello = default;
        Ack = default;
        Epoch = default;
        Request = default;
        Result = default;
        Fact = default;
        Variables = default;
    }

    private NetworkEnvelope(NetworkMessageKind kind, ulong sender, HelloMessage hello, HelloAckMessage ack, WorldEpochMessage epoch,
        CommandRequestMessage request, CommandResultMessage result, FactMessage fact, VariablesMessage variables)
    {
        Kind = kind;
        Sender = sender;
        Hello = hello;
        Ack = ack;
        Epoch = epoch;
        Request = request;
        Result = result;
        Fact = fact;
        Variables = variables;
    }

    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, HelloMessage hello) : this(kind, sender) => Hello = hello;
    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, HelloAckMessage ack) : this(kind, sender) => Ack = ack;
    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, WorldEpochMessage epoch) : this(kind, sender) => Epoch = epoch;
    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, CommandRequestMessage request) : this(kind, sender) => Request = request;
    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, CommandResultMessage result) : this(kind, sender) => Result = result;
    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, FactMessage fact) : this(kind, sender) => Fact = fact;
    internal NetworkEnvelope(NetworkMessageKind kind, ulong sender, VariablesMessage variables) : this(kind, sender) => Variables = variables;

    internal NetworkMessageKind Kind { get; }

    /// <summary>The sender SNet identifies on the receive callback, not a field the sender wrote.</summary>
    internal ulong Sender { get; }
    internal HelloMessage Hello { get; }
    internal HelloAckMessage Ack { get; }
    internal WorldEpochMessage Epoch { get; }
    internal CommandRequestMessage Request { get; }
    internal CommandResultMessage Result { get; }
    internal FactMessage Fact { get; }
    internal VariablesMessage Variables { get; }

    internal ushort ClaimedProtocol => Kind switch
    {
        NetworkMessageKind.Hello => Hello.ProtocolVersion,
        NetworkMessageKind.HelloAck => Ack.ProtocolVersion,
        NetworkMessageKind.WorldEpoch => Epoch.ProtocolVersion,
        NetworkMessageKind.CommandRequest => Request.ProtocolVersion,
        NetworkMessageKind.CommandResult => Result.ProtocolVersion,
        NetworkMessageKind.Fact => Fact.ProtocolVersion,
        NetworkMessageKind.Variables => Variables.ProtocolVersion,
        _ => 0
    };
}

/// <summary>One outgoing message: the kind tag the transport picks its event name from, plus the struct.</summary>
internal readonly struct NetworkMessage
{
    internal NetworkMessage(NetworkMessageKind kind, HelloMessage hello) : this(kind) => Hello = hello;
    internal NetworkMessage(NetworkMessageKind kind, HelloAckMessage ack) : this(kind) => Ack = ack;
    internal NetworkMessage(NetworkMessageKind kind, WorldEpochMessage epoch) : this(kind) => Epoch = epoch;
    internal NetworkMessage(NetworkMessageKind kind, CommandRequestMessage request) : this(kind) => Request = request;
    internal NetworkMessage(NetworkMessageKind kind, CommandResultMessage result) : this(kind) => Result = result;
    internal NetworkMessage(NetworkMessageKind kind, FactMessage fact) : this(kind) => Fact = fact;
    internal NetworkMessage(NetworkMessageKind kind, VariablesMessage variables) : this(kind) => Variables = variables;

    private NetworkMessage(NetworkMessageKind kind)
    {
        Kind = kind;
        Hello = default;
        Ack = default;
        Epoch = default;
        Request = default;
        Result = default;
        Fact = default;
        Variables = default;
    }

    internal NetworkMessageKind Kind { get; }
    internal HelloMessage Hello { get; }
    internal HelloAckMessage Ack { get; }
    internal WorldEpochMessage Epoch { get; }
    internal CommandRequestMessage Request { get; }
    internal CommandResultMessage Result { get; }
    internal FactMessage Fact { get; }
    internal VariablesMessage Variables { get; }
}