<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="NativeContracts\**\*.cs" />
    <Compile Include="..\PlayerTweaks.cs" Link="PlayerTweaks.cs" />
    <Compile Include="..\GameDataTweaks.cs" Link="GameDataTweaks.cs" />
    <Compile Include="..\CasualRules.cs" Link="CasualRules.cs" />
    <Compile Include="..\BoosterRollRules.cs" Link="BoosterRollRules.cs" />
    <Compile Include="..\StatisticRow.cs" Link="StatisticRow.cs" />
    <Compile Include="..\StatisticPeer.cs" Link="StatisticPeer.cs" />
    <Compile Include="..\StatisticsSync.cs" Link="StatisticsSync.cs" />
    <None Update="historical-stats.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
