<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Framework/ForgeRuntime.Framework.csproj" />
    <ProjectReference Include="../../../ForgeTrigger/ForgeTrigger.csproj" />
    <ProjectReference Include="../../../ForgeMap/ForgeMap.csproj" />
    <ProjectReference Include="../../../ForgeWeapon/ForgeWeapon.csproj" />
    <ProjectReference Include="../../../ForgeEnemy/ForgeEnemy.csproj" />
  </ItemGroup>
</Project>
