<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../ForgeRuntime/DiagnosticsReport.cs" Link="DiagnosticsReport.cs" />
    <Compile Include="../../../ForgeRuntime/AsyncReportWriter.cs" Link="AsyncReportWriter.cs" />
    <Compile Include="../../../ForgeRuntime/ProjectObjectReferences.cs" Link="ProjectObjectReferences.cs" />
  </ItemGroup>
</Project>
